name: news_feed_neoflex
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0+4
  sqflite_common_ffi: ^2.2.0
  path_provider: ^2.0.2
  image_picker: ^1.1.2
  permission_handler: ^12.0.0+1
  file_picker: ^10.1.2
  syncfusion_flutter_pdfviewer: ^29.1.40
  open_file: ^3.3.1
  dio: ^5.8.0+1
  shared_preferences: ^2.5.3
  flutter_appauth: ^9.0.0
  flutter_secure_storage: ^8.0.0
  flutter_riverpod: ^2.6.1
  oauth2: ^2.0.3
  oauth2_client: ^3.2.2
  built_collection: ^5.1.1
  openapi_generator_annotations: ^6.1.0
  get_it: ^8.0.3
  openapi:
    path: api
  flutter_bloc: ^9.1.0
  universal_html: ^2.2.4
  url_launcher: ^6.3.1
  crypto: ^3.0.6
  convert: ^3.1.2
  jwt_decode: ^0.3.1
  cached_network_image: ^3.4.1
  mime: ^2.0.0
  http_parser: ^4.1.2
  flutter_svg: ^2.1.0
  xml: ^6.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  openapi_generator: ^6.1.0
  openapi_generator_cli: ^6.1.0

flutter:
  uses-material-design: true  
  assets:
    - assets/images/
    - assets/images.json
    - assets/text/
    - assets/data.json
    - assets/office_map.svg
